// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARY70xWxdW5UXp9KTfGChLFLHSere_01E',
    appId: '1:617127359597:web:854bc3b89b4573623ffb64',
    messagingSenderId: '617127359597',
    projectId: 'verduleria-df26f',
    authDomain: 'verduleria-df26f.firebaseapp.com',
    storageBucket: 'verduleria-df26f.appspot.com',
    measurementId: 'G-Q9KVRBGSEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsjOtm_NzpCoCdTyHMm4mmnq5OeZK2hus',
    appId: '1:617127359597:android:404aa8d5ab1357473ffb64',
    messagingSenderId: '617127359597',
    projectId: 'verduleria-df26f',
    storageBucket: 'verduleria-df26f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuapXninaSbsnOkrsVdbkpNi1EEj84p5E',
    appId: '1:617127359597:ios:009a7e8cf3be3d8c3ffb64',
    messagingSenderId: '617127359597',
    projectId: 'verduleria-df26f',
    storageBucket: 'verduleria-df26f.appspot.com',
    iosBundleId: 'com.example.verduleria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuapXninaSbsnOkrsVdbkpNi1EEj84p5E',
    appId: '1:617127359597:ios:06f39da0b3d5cb733ffb64',
    messagingSenderId: '617127359597',
    projectId: 'verduleria-df26f',
    storageBucket: 'verduleria-df26f.appspot.com',
    iosBundleId: 'com.example.verduleria.RunnerTests',
  );
}
